sudo: required

language: generic

services:
 - docker

before_install:
 - echo "start creating an umage with dockerfile"
 - docker build -t ajw9491/docker-react-app -f Dockerfile.dev .

script:
 - docker run -e CI=true ajw9491/docker-react-app npm run test -- --coverage

after_success:
 - echo "Test  sucess"